project:
  type: website
  output-dir: _site

website:
  title: "Samad Roohi"
  description: "Weekly deep dives on NLP, RL and UQ."
  site-url: https://samadroohi.github.io/samadroohi.github.io/


  sidebar:
    collapse-level: 1
    contents:
      - section: "Series & Topics"
        contents:
          - posts/rl/index.qmd
          - posts/nlp/index.qmd
          - posts/ml/index.qmd
          - posts/uq/index.qmd

  page-footer:
    left: "© 2025 Samad Roohi"
    right:
      - text: "RSS"
        href: posts/index.xml
      - text: "Email"
        href: "mailto:samad.roohi@gmail.com"
      - text: "GitHub"
        href: "https://github.com/samadroohi"
      - text: "LinkedIn"
        href: "https://linkedin.com/in/samad-roohi-821a4b44"
      - text: "Twitter"
        href: "https://twitter.com/samad_ro"



format:
  html:
    theme: flatly
    toc: true
    code-copy: true
    highlight-style: github
    smooth-scroll: true
    navbar: false
    include-in-header:
      text: |
        <meta name="robots" content="index,follow" />
        <meta property="og:type" content="website" />
    include-after-body:
      text: |
        <!-- Simple contact link in footer already provided -->

execute:
  freeze: auto

metadata-files:
  - posts/_metadata.yml

profile:
  default: "default" 