project:
  type: website
  output-dir: _site

website:
  title: "Coming Soon"
  description: "Samad Roohi's Research Blog - Coming Soon"
  site-url: https://samadroohi.github.io/samadroohi.github.io/
  page-footer:
    left: "© 2025 Samad Roohi"
    right:
      - text: "Email"
        href: "mailto:samad.roohi@gmail.com"
      - text: "GitHub"
        href: "https://github.com/samadroohi"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-copy: true
    highlight-style: github
    smooth-scroll: true
    navbar: false
    include-in-header:
      text: |
        <style>
          body { font-family: 'Inter', sans-serif; background-color: #f8f9fa; color: #343a40; }
          h1 { color: #007bff; }
          h2 { color: #34495e; }
        </style>

execute:
  freeze: auto
