project:
  type: website
  output-dir: _site

website:
  title: "Samad Roohi"
  description: "Weekly insights on AI, Machine Learning, and Research"
  site-url: https://samadroohi.github.io/samadroohi.github.io/

  sidebar:
    collapse-level: 1
    contents:
      - section: "Weekly Insights"
        contents:
          - posts/index.qmd
      - section: "About"
        contents:
          - about.qmd
          - contact.qmd

  page-footer:
    left: "© 2025 Samad Roohi"
    right:
      - text: "RSS"
        href: posts/index.xml
      - text: "Email"
        href: "mailto:samad.roohi@gmail.com"
      - text: "LinkedIn"
        href: "https://linkedin.com/in/samad-roohi-821a4b44"
      - text: "Twitter"
        href: "https://twitter.com/samad_ro"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    highlight-style: github
    smooth-scroll: true
    navbar: false
    fig-cap-location: bottom
    df-print: kable
    css: styles.css
    include-in-header:
      text: |
        <meta name="robots" content="index,follow" />
        <meta property="og:type" content="website" />
        <meta name="author" content="Samad Roohi" />
        <meta name="keywords" content="AI, machine learning, research, weekly insights, NLP, RL, UQ" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">

execute:
  freeze: auto

metadata-files:
  - posts/_metadata.yml

profile:
  default: "default"
