project:
  type: website
  output-dir: _site

website:
  title: "Samad Roohi"
  description: "Weekly deep dives on NLP, RL and UQ."
  site-url: https://samadroohi.github.io/samadroohi.github.io/

format:
  html:
    theme: flatly
    navbar: false
    toc: false
    include-in-header:
      text: |
        <meta name="robots" content="index,follow" />
        <meta property="og:type" content="website" />
        <meta name="author" content="Samad Roohi" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <style>
          body { font-family: 'Inter', sans-serif; }
          h1 { color: #2c3e50; }
          h2 { color: #34495e; }
        </style>
